services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Flow\Service\:
    resource: '../../Service/*'
  flow.registry:
    alias: Flow\Service\Registry
    public: true

  Flow\Asset\AssetPackage:
    public: true
    arguments:
      $requestStack: '@request_stack'
    tags:
      - { name: 'assets.package', package: 'flow.assets.package' }
